### ISSUE TITLE
Convert O-RAN installation procedures to markdown/rst

### ISSUE THREAD

**Issue by jgaeddert** [openaicellular/oaic#1]
Tagging @pratheeksu for support.

Should not be committing `.docx` files as these do not play nice with Git. Need to convert this to proper format.

**Comment by joshuamoorexyz** [comment]
Point to sub modules in instillation documentation instead of hosted repository where changes will not be reflected.

**Comment by joshuamoorexyz** [comment]
@pratheeksu autoconf is a dependency for asn1 compiler under srsran-e2 instructions.

**Comment by jgaeddert** [comment]
Also libtool

**Comment by jgaeddert** [comment]
I think this one can be closed out as most of the documentation has been converted. Any lingering issues with the documentation can be assigned to a new issue.
