### ISSUE TITLE
Incorporate E2-like code into main branch

### ISSUE THREAD

**Issue by nathanstep55** [openaicellular/oaic#116]
srsRAN E2-like code and example xApps need to be implemented into the main branch. This means that any E2-like specific code needs to not interfere with existing E2 code. Make new repositories for the xApps and include srsRAN changes into the dedicated repository.

- [x] Include tmpfs documentation and srsRAN modifications to support it in e2like-doc branch
- [x] Ensure all modified code is accessible only through build flags
- [ ] Merge srsRAN E2-like into the main branch for srsRAN-e2 repository 
- [ ] Merge documentation to main branch for oaic repository

**Comment by jgaeddert** [comment]
Please split into sub-tasks, e.g. update documentation, update srsRAN-e2 repo to include e2-like build flag.
