### ISSUE TITLE
Support Non-RT RIC

### ISSUE THREAD

**Issue by jgaeddert** [openaicellular/oaic#119]
Expect release stand-alone Non-RT RIC

**Comment by joshuamoorexyz** [comment]
Expected Result: Components of NonRT RIC deploy without issue.

Issue: When running the script to install the nonrtric standalone components there is an error. The error is chart "nonrtric" matching not found in local index. No chart name found.


Steps to reproduce: 

 Clone down the repo and execute the following scripts

git clone "https://gerrit.o-ran-sc.org/r/it/dep"

git clone --recursive https://github.com/sebdet/oran-deployment.git

./dep/smo-install/scripts/layer-0/0-setup-microk8s.sh

./dep/smo-install/scripts/layer-0/0-setup-charts-museum.sh

./dep/smo-install/scripts/layer-0/0-setup-helm3.sh

./dep/smo-install/scripts/layer-1/1-build-all-charts.sh

	- ORAN "nonrtric" standalone:

./dep/smo-install/scripts/layer-2/2-install-nonrtric-only.sh standalone-nonrtric

**Comment by joshuamoorexyz** [comment]
Fixed this issue by the following:

As root,

cd dep/smo-install/oran_oom

make all


Now the chart is available, but the erorr is in helm-override/standalone-nonrtric/oran-override.yaml file is not available.

**Comment by joshuamoorexyz** [comment]
Fixed this issue as well. (see below) Wen is going to create some documentation with all these fixes inline, can someone help with writing instructions on using the nonrtric setup possibly onboarding an rapp, accessing the control panel, etc?

![nonrtric](https://github.com/openaicellular/oaic/assets/40312633/38295cba-1d49-4828-8dad-bedd74860ffb)
