### ISSUE TITLE
Video example installation and running xapps (KPIMON and Nextran)

### ISSUE THREAD

**Issue by joshuamoorexyz** [openaicellular/oaic#13]
Fully detail installation of environment for xapps (KPIMON and Nextan)
Show how to run and major features of xapp.

**Comment by talhafaizurrahman** [comment]
@joshuamoorexyz the documentation looks alright to me. @pratheeksu can comment on code lines.

**Comment by jgaeddert** [comment]
NextRAN xApp is not associated with the Code 1 release. Should we remove that from the requirement of this issue?

**Comment by pratheeksu** [comment]
MReza has uploaded the videos to [OAIC Youtube channel](https://www.youtube.com/channel/UCpp9hpRisjMP2gwR5OGEmVQ)
