### ISSUE TITLE
config-file.json Error during Nexran xApp Deployment

### ISSUE THREAD

**Issue by casperfox** [openaicellular/oaic#136]
When trying to deploy the Nexran xApp, in which I am on this step: [https://openaicellular.github.io/oaic/nexran1.html#deploying-the-xapp](url)

When I enter:
`curl -L -X POST "http://$KONG_PROXY:32080/onboard/api/v1/onboard/download" --header 'Content-Type: application/json' --data-binary "@nexran-onboard.url"`

I get this as its output:
`{`
`    "error_source": "config-file.json",`
`    "error_message": "Wrong response code: 404, <html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n",`
`    "status": "Downloading config-file.json failed"`
`}`

I even went back to the xApp Deployment - General Guidelines page to see if I missed anything. I am not sure what is going on with it.

Here is what is in my nexran-onboard.url file:
`{"config-file.json_url":"http://192.168.122.182:5010/config-file.json"}`

Here is what is in my xApp_config.local.conf file located in /etc/nginx/conf.d:
![image](https://github.com/openaicellular/oaic/assets/139652780/b4cd76da-8c32-4cde-9854-d864e24d740f)

Any help would be appreciated!

**Comment by jcboone** [comment]
Hi! I also had this issue. It's not the config file, there's a typo in the nexran-onboard.url file. The config file in the directory that you copy into the server from the xApp Deployment - General Guidelines is named config-file.json but the onboard file assumes it's called nexran-config-file.json. You can either rename the config file or modify the onboard file.

**Comment by joshuamoorexyz** [comment]
> Hi! I also had this issue. It's not the config file, there's a typo in the nexran-onboard.url file. The config file in the directory that you copy into the server from the xApp Deployment - General Guidelines is named config-file.json but the onboard file assumes it's called nexran-config-file.json. You can either rename the config file or modify the onboard file.

Yes this seems to be the issue. I will commit the change thanks!

**Comment by casperfox** [comment]
What I did to fix this issue was I change the directory in the nexran-onboard.url file from:

`{"config-file.json_url":"http://192.168.122.182:5010/config-file.json"}`
to
`{"config-file.json_url":"http://192.168.122.182:5010/config_files/config-file.json"}`

and that resolved my problem. I just had to had /config_files in and it worked fine.
