### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by mrkouchaki** [openaicellular/oaic#18]
When running ./gen-cloud-init.sh command ubuntu 20.04 is not allowed in generated shell script " ./k8s-1node-cloud-init-k_1_16-h_2_17-d_cur.sh " file. I added below lines manually and it worked for me.

**elif [[ ${UBUNTU_RELEASE} == 20.* ]]; then
  echo "Installing on Ubuntu $UBUNTU_RELEASE (Bionic Beaver)"
  if [ ! -z "${DOCKERV}" ]; then
    DOCKERVERSION="${DOCKERV}-0ubuntu1~20.04.4"
  fi**

![change-1](https://user-images.githubusercontent.com/93693562/165344092-c76a2a7b-dc59-418e-adb7-00dac4e5693b.jpg)
![IMG-4339 (1)](https://user-images.githubusercontent.com/93693562/165344259-9be72086-0d9a-4775-abca-5f9715381e9d.jpg)

**Comment by jgaeddert** [comment]
There is an `ubuntu20.04` branch to address this, and I've made a [similar change in the RIC-Deployment](https://github.com/openaicellular/RIC-Deployment/compare/aed39eed3108410e207827c54b103581e45ae3ed...afbe0e64f25ec58d89da413aeb28e0c3d03b69c5#diff-475a1ec3b60cf62f9d658b43bf6dceaac1d7692a521fd429fd660c24de1162ad) submodule

**Comment by pratheeksu** [comment]
Merged changes into branch.
