### ISSUE TITLE
Arrange documentation

### ISSUE THREAD

**Issue by joshuamoorexyz** [openaicellular/oaic#22]
Installation Procedures Section:
+ Xapp Deployment Section:
+Create new page "Xapp Development"
- include getting started developing xapps
- include helloworld xapp code and deployment
- xapp frame
- Software Installation and deployment

+ Create new page "Xapp deployment"
+new page with explicit instructions for kpimon
-include xapp deployment - general guidelines

remove "Create an xApp Image Registry[](https://openaicellular.github.io/oaic/xapp_deployment.html#create-an-xapp-image-registry)

First we need to create a registry to host our xApp images. Here we create a local docker registry called xApp-registry.local:5008. 5008 indicates the port number on which the registry is listening"

remove "DMS-CLI Deployment"
+ make new page

**Comment by pratheeksu** [comment]
Merged all changes
