### ISSUE TITLE
Create VM image with full development environment

### ISSUE THREAD

**Issue by joshuamoorexyz** [openaicellular/oaic#23]

**Comment by jgaeddert** [comment]
Is the intent here to have a VM that the community can download and use? Any objection to using a docker image instead of a VM?

**Comment by romilbalar** [comment]
Doc for creating a base box: https://github.com/openaicellular/oaic/blob/vagrant-dev/Create_base_box

**Comment by romilbalar** [comment]
Bash script to automate the 'Setup your 5G Network step' : https://github.com/openaicellular/oaic/blob/vagrant-dev/setup5GNetwork.sh
