### ISSUE TITLE
Cannot find srsRAN/config_files/core_config_files/ in 5G SA

### ISSUE THREAD

**Issue by mrkouchaki** [openaicellular/oaic#26]
after installing srsRAN for 5g SA, I dont have srsRAN/config_files/ directory.

**Comment by romilbalar** [comment]
@mrkouchaki Were you able to resolve this issue?

**Comment by romilbalar** [comment]
I solved this by running the 'srsran_install_config.sh' with root privileges ('sudo' before it)

This command is the last one in 'srsRAN with E2 agent Installation'.

**Comment by mrkouchaki** [comment]
Yes, solved.
