### ISSUE TITLE
Problems with installing the RIC platform

### ISSUE THREAD

**Issue by romilbalar** [openaicellular/oaic#31]
After following along with the documentation to install the RIC platform (https://docs.o-ran-sc.org/projects/o-ran-sc-ric-plt-ric-dep/en/latest/installation-guides.html), I am unable to see results as expected for the commands "helm list" (shows no output). The command "kubectl get pods -n ricinfra"  shows a pod with status "ImagePullBackOff".

**Comment by jgaeddert** [comment]
@romilbalar are you following the instructions here? https://openaicellular.github.io/oaic/oran_installation.html

**Comment by romilbalar** [comment]
I am, I was led to
https://docs.o-ran-sc.org/projects/o-ran-sc-ric-plt-ric-dep/en/latest/installation-guides.html,
after finishing the installation steps under Step 1: Install and configure
an Ubuntu Host Machine/ Virtual Machine (VM): VM configuration instructions.
