### ISSUE TITLE
Problem with step: "Setup your own 5G Network"

### ISSUE THREAD

**Issue by romilbalar** [openaicellular/oaic#32]
**command:** 
sudo srsepc

**Error encountered:**
Couldn't open , trying /home/srsran2/.config/srsran/epc.conf
Reading configuration file /home/srsran2/.config/srsran/epc.conf...
Couldn't open user_db.csv, trying /home/srsran2/.config/srsran/user_db.csv
HSS Initialized.
MME S11 Initialized
MME GTP-C Initialized
MME Initialized. MCC: 0xf001, MNC: 0xff01
SPGW GTP-U Initialized.
SPGW S11 Initialized.
SP-GW Initialized.

Steps to reproduce:
Finish steps 1 & 2 successfully (O-RAN and srsRAN setup respectively)
run command: sudo srsepc

**Comment by jgaeddert** [comment]
Thanks @romilbalar. Seems like there are some missing files?

**Comment by pratheeksu** [comment]
This is not an error. This is expected behavior. If no file is given as input arg, then srsepc reads config files from default locations. In this case the default location is "/home/srsran2/.config/srsran/". All the components of the EPC are initialized as seen above

**Comment by romilbalar** [comment]
I get a similar output when I run the next command-

command: sudo srsenb

Output:
Couldn't open , trying /home/srsran2/.config/srsran/enb.conf
Reading configuration file /home/srsran2/.config/srsran/enb.conf...
Couldn't open sib.conf, trying /home/srsran2/.config/srsran/sib.conf
Couldn't open rr.conf, trying /home/srsran2/.config/srsran/rr.conf
Couldn't open rb.conf, trying /home/srsran2/.config/srsran/rb.conf
WARNING: Could not verify cpu0 scaling governor
WARNING: Could not verify cpu1 scaling governor
WARNING: Could not verify cpu2 scaling governor
WARNING: Could not verify cpu3 scaling governor

Built in RelWithDebInfo mode using commit f226378 on branch HEAD.

connect(): Connection refused
Failed to initiate S1 connection. Attempting reconnection in 10 seconds
Opening 1 channels in RF device=default with args=default
Available RF device list: UHD  zmq 
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 7.5.0; Boost_106501; UHD_4.2.0.0-0ubuntu1~bionic1
[INFO] [LOGGING] Fastpath logging disabled at runtime.
[ERROR] [UHD] Device discovery error: receive_from: Connection refused
Opening USRP channels=1, args: type=x300,master_clock_rate=184.32e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [X300] X300 initialization sequence...

**Comment by jgaeddert** [comment]
Need to configure to use USRPs with proper image (try 192.168.40.202 and 192.168.40.201)

**Comment by jgaeddert** [comment]
Apparently some of the USRPs don't have the right base FPGA image loaded; however installing new images will cause things to break. We should focus on those which have the proper images installed.

**Comment by jgaeddert** [comment]
Full command:

```
sudo srsenb --enb.n_prb=15 --enb.name=enb1 --enb.enb_id=0x19B \
--rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://localhost:2001,tx_port1=tcp://*:2100,rx_port1=tcp://localhost:2101,id=enb,base_srate=23.04e6" \
--ric.agent.remote_ipv4_addr=${E2TERM_IP} --log.all_level=warn --ric.agent.log_level=debug --log.filename=stdout --ric.agent.local_ipv4_addr=${E2NODE_IP} --ric.agent.local_port=${E2NODE_PORT}
```

**Comment by pratheeksu** [comment]
For CORNET the command with IP address will be,

`sudo srsenb --enb.name=enb1 --enb.enb_id=0x19B \
--rf.device_name=uhd --rf.device_args="type=x300,addr=192.168.40.201,clock=internal,sampling_rate=11.52e6,lo_freq_offset_hz=23.04e6,send_frame_size=8000,recv_frame_size=8000,num_send_frames=64,num_recv_frames=64,None" \
--ric.agent.remote_ipv4_addr=${E2TERM_IP} --log.all_level=warn --ric.agent.log_level=debug --log.filename=stdout --ric.agent.local_ipv4_addr=${E2NODE_IP} --ric.agent.local_port=${E2NODE_PORT}`

**Comment by jgaeddert** [comment]
Are those environment variables set up in previous commands?

**Comment by pratheeksu** [comment]
Yeah. It wasn't showing up because of a documentation bug. Fixed it.

**Comment by romilbalar** [comment]
@pratheeksu 
I believe there is still an error.

command:export E2TERM_IP=`sudo kubectl get svc -n ricplt --field-selector metadata.name=service-ricplt-e2term-sctp-alpha -o jsonpath='{.items[0].spec.clusterIP}'`

error: error executing jsonpath "{.items[0].spec.clusterIP}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].spec.clusterIP}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}

**Comment by pratheeksu** [comment]
kubectl is not able to find the pod. The message says index and lengths are both 0. Make sure the pod is deployed and is in "running" state.
