### ISSUE TITLE
'Did not find expected key' error 

### ISSUE THREAD

**Issue by romilbalar** [openaicellular/oaic#34]
I noticed that on step 4 of the 'Near-Real Time RIC Installation Procedure', I run into the following error:

Error: failed to parse ../RECIPE_EXAMPLE/PLATFORM/example_recipe_oran_e_release_modified_e2.yaml: error converting YAML to JSON: yaml: line 113: did not find expected key

command run: cd RIC-Deployment/bin
sudo ./deploy-ric-platform -f ../RECIPE_EXAMPLE/PLATFORM/example_recipe_oran_e_release_modified_e2.yaml

Is there something missing or is this a non-issue for the overall build?

**Comment by pratheeksu** [comment]
This is due to an extra indent for the key in line 113 .This has been fixed
