### ISSUE TITLE
Parse documentation and create bash script for installation & testing

### ISSUE THREAD

**Issue by jgaeddert** [openaicellular/oaic#36]
Start with installation of O-RAN, near RT-RIC, srsRAN and e2 agent. Pull out `.rst` code blocks marked as `:: bash` and generate `.sh` file that can be run in a VM or possibly a Docker container.

**Comment by jgaeddert** [comment]
./generate_install_script.py docs/source/oran_installation.rst docs/source/srsRAN_installation.rst -o install.sh

**Comment by romilbalar** [comment]
Under Testing: https://github.com/openaicellular/oaic/tree/installation_script

**Comment by jgaeddert** [comment]
Running late
