### ISSUE TITLE
Flannel will not deploy in O-RAN near-RT RIC installation

### ISSUE THREAD

**Issue by nathanstep55** [openaicellular/oaic#38]
**Issue:** When running the `k8s-1node-cloud-init-k_1_16-h_2_17-d_cur.sh` script as part of the installation for the near-RT RIC, when applying the `kube-flannel.yml` located [here](https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml), Flannel never deploys and CoreDNS will remain pending.

**Reason:** A commit last month in the `flannel-io/flannel` repository removes the PodSecurityPolicy in `kube-flannel.yml` and moves it to [`kube-flannel-psp.yml`](https://github.com/flannel-io/flannel/commit/d6ad1c1eb36d850456417880b6ee57af68661036#diff-e12539ca526d07185b3d16099b32ff84530f80eca7616d4a17d7c7975531c531)

**Solution:** In the `k8s_vm_install.sh` script used in RIC-Deployment, replace the `kube-flannel.yml` link with one from before the problematic commit: https://raw.githubusercontent.com/flannel-io/flannel/9de10c12c8266b0cfe09bc0d5c969ae28832239f/Documentation/kube-flannel.yml
An alternative (and more futureproof solution) is to apply both `kube-flannel.yml` and `kube-flannel-psp.yml` from the repository. I have not tested this, so I cannot confirm if it works or not.

**Comment by joshuamoorexyz** [comment]
Should be fixed when changes are merged from this commit https://github.com/openaicellular/RIC-Deployment/pull/2/commits/2379e43211b87719e0a309a24d44fa46ed048505
