### ISSUE TITLE
Symbolic links to config files - Web server

### ISSUE THREAD

**Issue by pratheeksu** [openaicellular/oaic#40]
The xApp config files are copied to the directory accessible by the web server. This means that every time we change the config file we will need to replace it in the web server accessible directory. This is fine for users planning to test out our platforms but during development of new xApps this can prove to be a tedious task. 

Instead we can use symbolic links to config files, so that whenever a change is made we do not need to copy paste the updated file. We can explore other more efficient methods as well.

Thanks to Joao Santos for suggesting this.

**Comment by joshuamoorexyz** [comment]
I have opened a branch here: https://github.com/openaicellular/oaic/tree/40-symbolic-links-to-config-files-web-server

I will work on this issue there.
