### ISSUE TITLE
OAIC Installation Error

### ISSUE THREAD

**Issue by hridweekkarki** [openaicellular/oaic#43]
While trying to configure OAIC, I am stuck while trying to run the script k8s-1node-cloud-init-k_1_16-h_2_17-d_cur.sh in the directory oaic/RIC-Deployment/tools/k8s/bin/. I have added the script and the stack trace file below.

[stacktrace.txt](https://github.com/openaicellular/oaic/files/9311573/stacktrace.txt)

**Comment by pratheeksu** [comment]
Hi,

It looks like you don't have enough system resources. That's why some of the pods are evicted during your installation. If you are working on a VM consider allocating more CPUs, RAM and storage.

**Comment by hridweekkarki** [comment]
Hello,

Thanks for getting back to me.

Yes, I am working on a VM. I just wanted to ask what are the minimum
resources I should allocate to it.

Thanks & Regards,
Hridweek Karki

**Comment by pratheeksu** [comment]
Hi, 

Minimum requirements: 

CPU cores: 4
Freq: > 3.5 GHz
RAM: 8 GB
Storage: 80 GB

Recommended requirements:

CPU cores: 8
Freq: > 4.0 GHz
RAM: 16 GB
Storage: 100 GB

**Comment by joshuamoorexyz** [comment]
This issue seems to be resolved, so i will close.
