### ISSUE TITLE
waiting for 5/8 pods running in namespace

### ISSUE THREAD

**Issue by natanzi** [openaicellular/oaic#48]
In step 3, after running  sudo ./k8s-1node-cloud-init-k_1_16-h_2_17-d_cur.sh , script struggled in the loop:

+ echo '> waiting for 5/8 pods running in namespace [kube-system] with keyword [Running]'
> waiting for 5/8 pods running in namespace [kube-system] with keyword [Running]
+ '[' 5 -lt 8 ']'
+ sleep 5

**Comment by natanzi** [comment]
For virtual Box user this issue related to the count of the cpu and core, it should be more than 1 because of the docker.

**Comment by jgaeddert** [comment]
What version of ubuntu vbox are you running?

**Comment by natanzi** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename: bionic
with multiple VCPU and 32 GIG RAM

**Comment by jgaeddert** [comment]
I'm hitting the same issue. I thought we had this resolved.

**Comment by jgaeddert** [comment]
Try pulling master and updating the submodules (specifically the RIC-deployment repo). Core wasn't pointing to the latest commit on master.
