### ISSUE TITLE
nexRAN xapp can't send control request to enb

### ISSUE THREAD

**Issue by sareek** [openaicellular/oaic#53]
Steps to reproduce the problem:
1.  Get 5G tesbed ready following OAIC documentation and have epc, enB and ue running and nexRAN xapp deployed. 
2.   Do POST request to add eNB so that eventually, you will be able to bind "fast" and "slow" slices to the eNB and bind UE to fast or slow slice.  

Expected output with nexran logs VS real output:
On nexran logs I should have got message "sent control request" after initialing subscription request. 
Actual output: No such message

On Base Station side,
I should have got,  <RICcontrolRequest>
Actual missing <RICcontrolRequest>. Instead, I get first, RicSubscription request, message for "Received RICsubscription Request", <RICsubscriptionResponse> and just metrices from UE in loop. 

Here are nexran logs and base station logs along with actual expected outcome:

**Actual expected outcome:**
Nexranlog
![Screenshot 2022-10-28 155809](https://user-images.githubusercontent.com/16555225/198721841-cebcfe9f-4a68-4bb6-a4f6-d9f3d885656f.png)

**Base Station Side**
![Screenshot 2022-10-28 155935](https://user-images.githubusercontent.com/16555225/198722088-6e972f4f-e211-4cc6-b53d-85e14d8050e1.png)

Nexran logs:
[nexran-logs.txt](https://github.com/openaicellular/oaic/files/9891399/nexran-logs.txt)

Screenshot: See after requestor ID, "sent control request message is missing" See above logs for full log.
![Screenshot 2022-10-28 160418](https://user-images.githubusercontent.com/16555225/198722815-ae482519-c0ca-4bcf-b675-69ab0ff89ba0.png)

Base station logs
[bs_log_nexran.txt](https://github.com/openaicellular/oaic/files/9891400/bs_log_nexran.txt)

Note that I am able to create slice, ues, add enbs. But since, enb and xapp's connection has some problem. Resources are not being allocated as required. So, even if I allocate UE to slow slice there is not change in data transfer rate between UE and network.

**Comment by mdalgitsis** [comment]
Hello @sareek 

I am trying to deploy the NexRAN xAPP but I am having some issues when I run the srsran enb. I receive a message the the --slicer.enable=1 option is unrecognized. I see that following the guilines on the installation part of srsran the options regarding NexRAN are OFF. After I enable then ON, I have errors when I install again the srsran.

How did you install srsran with the RAN slicer?

I also started a discussion here if anyone can help me: https://github.com/openaicellular/oaic/discussions/85

**Comment by mdalgitsis** [comment]
> I believe this has already been addressed. I will close for now

Where it has been addressed?

**Comment by mdalgitsis** [comment]
Thank you very much for your reply
