### ISSUE TITLE
Error: release r4-e2term failed: Service "service-ricplt-e2term-sctp-alpha" is invalid: spec.ports[0].protocol: Unsupported value: "SCTP": supported values: "TCP", "UDP"

### ISSUE THREAD

**Issue by liuzong2022** [openaicellular/oaic#54]
Hi,
  when I executed this command to deploy ric, an error occurred. So when I setup my own 5G network, service-ricplt-e2term-sctp-alpha was found.
  sudo ./deploy-ric-platform -f ../RECIPE_EXAMPLE/PLATFORM/example_recipe_oran_e_release_modified_e2.yaml
  an error occurred:
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading ric-common from repo http://127.0.0.1:8879/charts
Deleting outdated charts
Error: release r4-e2term failed: Service "service-ricplt-e2term-sctp-alpha" is invalid: spec.ports[0].protocol: Unsupported value: "SCTP": supported values: "TCP", "UDP"
when I execuyed this command : kubectl get svc -n ricplt --field-selector metadata.name=service-ricplt-e2term-sctp-alpha
No resources found in ricplt namespace.

kubectl get svc -n ricplt
NAME                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                           AGE
aux-entry                                   ClusterIP   10.111.240.79    <none>        80/TCP,443/TCP                    47m
r4-infrastructure-kong-proxy                NodePort    10.109.94.119    <none>        32080:32080/TCP,32443:32443/TCP   47m
r4-infrastructure-prometheus-alertmanager   ClusterIP   10.96.113.213    <none>        80/TCP                            47m
r4-infrastructure-prometheus-server         ClusterIP   10.102.8.5       <none>        80/TCP                            47m
ricplt-influxdb                             ClusterIP   10.97.139.248    <none>        8086/TCP,8088/TCP                 18m
service-ricplt-a1mediator-http              ClusterIP   10.107.241.10    <none>        10000/TCP                         28m
service-ricplt-a1mediator-rmr               ClusterIP   10.103.24.82     <none>        4561/TCP,4562/TCP                 28m
service-ricplt-alarmmanager-http            ClusterIP   10.102.208.6     <none>        8080/TCP                          20m
service-ricplt-alarmmanager-rmr             ClusterIP   10.102.188.206   <none>        4560/TCP,4561/TCP                 20m
service-ricplt-appmgr-http                  ClusterIP   10.107.175.50    <none>        8080/TCP                          39m
service-ricplt-appmgr-rmr                   ClusterIP   10.108.153.62    <none>        4561/TCP,4560/TCP                 39m
service-ricplt-dbaas-tcp                    ClusterIP   None             <none>        6379/TCP                          45m
service-ricplt-e2mgr-http                   ClusterIP   10.106.190.81    <none>        3800/TCP                          34m
service-ricplt-e2mgr-rmr                    ClusterIP   10.98.227.250    <none>        4561/TCP,3801/TCP                 34m
service-ricplt-e2term-prometheus-alpha      ClusterIP   10.107.94.0      <none>        8088/TCP                          31m
service-ricplt-e2term-rmr-alpha             ClusterIP   10.109.190.178   <none>        4561/TCP,38000/TCP                31m
service-ricplt-jaegeradapter-agent          ClusterIP   10.109.193.226   <none>        5775/UDP,6831/UDP,6832/UDP        17m
service-ricplt-jaegeradapter-collector      ClusterIP   10.98.168.34     <none>        14267/TCP,14268/TCP,9411/TCP      17m
service-ricplt-jaegeradapter-query          ClusterIP   10.106.84.73     <none>        16686/TCP                         17m
service-ricplt-o1mediator-http              ClusterIP   10.96.142.139    <none>        9001/TCP,8080/TCP,3000/TCP        23m
service-ricplt-o1mediator-tcp-netconf       NodePort    10.98.37.37      <none>        830:30830/TCP                     23m
service-ricplt-rtmgr-http                   ClusterIP   10.108.156.252   <none>        3800/TCP                          37m
service-ricplt-rtmgr-rmr                    ClusterIP   10.105.255.237   <none>        4561/TCP,4560/TCP                 37m
service-ricplt-submgr-http                  ClusterIP   None             <none>        3800/TCP                          26m
service-ricplt-submgr-rmr                   ClusterIP   None             <none>        4560/TCP,4561/TCP                 26m
service-ricplt-vespamgr-http                ClusterIP   10.99.186.75     <none>        8080/TCP,9095/TCP                 25m
service-ricplt-xapp-onboarder-http          ClusterIP   10.104.85.80     <none>        8888/TCP,8080/TCP                 42m

**Comment by pratheeksu** [comment]
Can you provide some details regarding the system configuration and the operating system?

**Comment by joshuamoorexyz** [comment]
@liuzong2022 Is this still an issue and if so can you update with more information as requested? If it is solved, we can close the issue as resolved.

**Comment by romilbalar** [comment]
Marking as stale.
