### ISSUE TITLE
-ric.agent.remote_ipv4_addr' should follow immediately after the equal sign

### ISSUE THREAD

**Issue by Chi-Hsin-Wu** [openaicellular/oaic#55]
Hello, I'm trying to set up my own 5G network with oaic.
But when I'm trying to setup the srsenb with zmq, it replies me with the issue"-ric.agent.remote_ipv4_addr' should follow immediately after the equal sign"
please help me deal with it.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/102419877/203748412-8f34dbf4-8116-48ad-9d99-505fd8afd105.png">

**Comment by pratheeksu** [comment]
The whole command should be in a single line. You have pasted it incorrectly.

Here try this: `sudo srsenb --enb.n_prb=50 --enb.name=enb1 --enb.enb_id=0x19B --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://localhost:2001,tx_port1=tcp://*:2100,rx_port1=tcp://localhost:2101,id=enb,base_srate=23.04e6" --ric.agent.remote_ipv4_addr=${E2TERM_IP} --log.all_level=warn --ric.agent.log_level=debug --log.filename=stdout --ric.agent.local_ipv4_addr=${E2NODE_IP} --ric.agent.local_port=${E2NODE_PORT}`

**Comment by joshuamoorexyz** [comment]
This happens because the export commands have not properly been done. Please follow the instructions above this command and it will fix the issue.
