### ISSUE TITLE
Issue with multiUE simulation

### ISSUE THREAD

**Issue by shrsam** [openaicellular/oaic#57]
Hello,

When I am trying with a multi-UE setup with the commands as listed, I am getting the following error. What should be the port values to be entered for Port0 and Port1. Could you please provide the modified command for setting up srsue

root@shreyas-VirtualBox:~# sudo srsue /home/shreyas/.config/srsran/ue.conf --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2010,rx_port=tcp://localhost:2008,id=ue1,base_srate=23.04e6" --gw.netns=ue1 --usim.algo=xor --usim.imsi=001010123456789
Reading configuration file /home/shreyas/.config/srsran/ue.conf...

Built in RelWithDebInfo mode using commit eee2bbf on branch HEAD.

Opening 2 channels in RF device=zmq with args=fail_on_disconnect=true,tx_port=tcp://*:2010,rx_port=tcp://localhost:2008,id=ue1,base_srate=23.04e6
Available RF device list: UHD  zmq 
CHx base_srate=23.04e6
CHx id=ue1
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
CH0 rx_port=tcp://localhost:2008
CH0 tx_port=tcp://*:2010
CH0 fail_on_disconnect=true
[zmq] ue1 Tx port not specified. Disabling transmitter.
[zmq] ue1 Rx port not specified. Disabling receiver.
[zmq] Error: Neither Tx port nor Rx port specified.
Error initializing radio.

**Comment by joshuamoorexyz** [comment]
This will be uploaded and built with the documentation, but for now please follow the document here. You will need to change the gnuradio file (broker) to support the amount of UEs you want. https://github.com/joshuamoorexyz/srsran-5g-zmq-multi-UE/blob/main/multi_ue_example_with_5g.rst
