### ISSUE TITLE
kpimon Docker problem

### ISSUE THREAD

**Issue by mrkouchaki** [openaicellular/oaic#62]
Docker build problem

**Comment by mrkouchaki** [comment]
It seems the nexus3 Repo for go:1.0.0 has problem, please changed it to go:1.1.0 as kpimonbuild

**Comment by pratheeksu** [comment]
Pulling from `nexus3.o-ran-sc.org:10002 `instead of `nexus3.o-ran-sc.org:10002`.

The modified line in the DockerFile now is 

`FROM nexus3.o-ran-sc.org:10002/o-ran-sc/bldr-ubuntu20-c-go:1.0.0 as kpimonbuild`
