### ISSUE TITLE
Nexran unable to deploy on e-release of near real time ric using dms_cli tool

### ISSUE THREAD

**Issue by wchen2654** [openaicellular/oaic#71]
I'm trying to run nexran xapp on the e-release of the near real time ric using the dms_cli xapp_onboarder tool. Here's the problem that I'm facing:
  
When running this command dms_cli install --xapp_chart_name=nexran --version=0.1.0 --namespace=ricxapp, it states an error showing how there is a missing chart name, contradicting the fact that there is already a chart name stated in the --xapp_chart_name variable.

How to reproduce:

1. Obtain the xapp-embedded-schema.json from the nexran repo on github	# I put this file under the nexran directory which is located under the oaic directory

2. Create a local helm repository with a port other than 8080 on host
docker run --rm -u 0 -it -d -p 8090:8080 -e DEBUG=1 -e STORAGE=local -e STORAGE_LOCAL_ROOTDIR=/charts -v $(pwd)/charts:/charts chartmuseum/chartmuseum:latest

3. Set an environment variable for Chart repo
export CHART_REPO_URL=http://0.0.0.0:8090

4. Install the dms_cli tool  # Website that I used: https://docs.o-ran-sc.org/projects/o-ran-sc-ric-plt-ric-dep/en/latest/installation-guides.html

sudo -i								# I had to go to super user to download dms_cli due to a permission error later on
git clone "https://gerrit.o-ran-sc.org/r/ric-plt/appmgr"		# I cloned this under the oaic repository
cd appmgr/xapp_orchestrater/dev/xapp_onboarder
sudo apt install python3-pip						# Python3 is required for this
pip3 install ./							# Installs xapp_onboarder

5. Set permissions to non-root users for certain files
sudo chmod 755 /usr/local/bin/dms_cli
sudo chmod -R 755 /usr/local/lib/python3.6
sudo chmod -R 755 /usr/local/lib/python3.6

6. Onboard the xApp
dms_cli onboard ~/home/<user_name>/oaic/nexran/nextran-config-file.json ~/home/<user_name>/oaic/nexran/xapp-embedded-schema.json

7. Deploying the xApp *The Error*
dms_cli install --xapp_chart_name=nexran --version=0.1.0 --namespace=ricxapp

**Comment by wchen2654** [comment]
I have mangaged to deploy the nexran xApp on the e release of the near real time ric, but instead of using the dms_cli tool, I used the dawn release instructions on POWDER. However, I have encountered another problem when running these commands:

export NEXRAN_XAPP=`kubectl get svc -n ricxapp --field-selector metadata.name=service-ricxapp-nexran-rmr -o jsonpath='{.items[0].spec.clusterIP}'` ; echo $NEXRAN_XAPP
curl -i -X GET http://${NEXRAN_XAPP}:8000/v1/version ; echo ; echo

Here is the error output:
curl: (7) Failed to connect to 10.97.254.129 port 8000: Connection refused

How to reproduce: # I ran all of this under the Nexran repository

1. Deploy the near real time ric using e release recipe

2. Onboard the Nexran xApp
export KONG_PROXY=`kubectl get svc -n ricplt -l app.kubernetes.io/name=kong -o jsonpath='{.items[0].spec.clusterIP}'`
curl -L -X POST "http://${KONG_PROXY}:32080/onboard/api/v1/onboard/download" --header 'Content-Type: application/json' --data-binary "@nexran-onboard.url"
  
3. Obtain the Helm chart to see if the xApp was onboarded
curl -L -X GET "http://${KONG_PROXY}:32080/onboard/api/v1/charts"

4. Deploy the Nexran xApp
curl -L -X POST "http://${KONG_PROXY}:32080/appmgr/ric/v1/xapps" --header 'Content-Type: application/json' --data-raw '{"xappName": "nexran"}'

5. Trying to talk to the Nexran xApp / The Error
export NEXRAN_XAPP=`kubectl get svc -n ricxapp --field-selector metadata.name=service-ricxapp-nexran-rmr -o jsonpath='{.items[0].spec.clusterIP}'` ; echo $NEXRAN_XAPP
curl -i -X GET http://${NEXRAN_XAPP}:8000/v1/version ; echo ; echo

I also have ran this command if it helps to reproduce this error:
sudo docker build . -t xApp-registry.local:5008/nexran:0.1.0

**Comment by sareek** [comment]
"
curl: (7) Failed to connect to 10.97.254.129 port 8000: Connection refused"

Hello,
Can you please attach the whole error message?

Also, have you tried restarting the xApp with sudo kubectl rollout restart deployment ricxapp-nexran?
Also, check logs of nexran xapp after re-deployement, you should see something like this, 
![Screenshot 2023-01-16 121003](https://user-images.githubusercontent.com/16555225/212733595-7364b832-1eb3-44d8-ad8b-9be086919611.png)

**Comment by joshuamoorexyz** [comment]
![services](https://user-images.githubusercontent.com/40312633/213300086-e4f98729-94e6-49d7-a7dc-6a6c4317a01e.png)
My services show this, can you please show yours? After our meeting today, pratheek said it may be a services issue. 
@sareek @nathanstep55

**Comment by sareek** [comment]
@joshuamoorexyz Hello, for u is it working, are u able to control UE through with nexran xapp?

Here is ss for services, 
<img width="519" alt="Screenshot 2023-01-18 190246" src="https://user-images.githubusercontent.com/16555225/213324576-3173cde1-1a49-4f19-bcfc-eb4bc690cf11.png">

**Comment by wchen2654** [comment]
Managed to deployed the nexran xApp to the e/f-release of the near real time ric by using Helm version 3
