### ISSUE TITLE
Connection between UE and ENB lost after several seconds

### ISSUE THREAD

**Issue by jqhu27** [openaicellular/oaic#80]
The srsUE can attach to the network at the first several seconds and the assigned IP address can be seen from the terminal. But after several seconds, the connection is lost and I cannot ping srsUE from srsEPC or vice versa. 

I use two USRP X310 with 1 Gbps NIC laptops. Not sure whether the 1 Gbps NIC is the reason. Has anyone met similar problem before?  

![srsEPC](https://user-images.githubusercontent.com/54186610/225756425-51b101b6-3635-474c-93bc-8b9370bc8fa8.png)
![srsENB](https://user-images.githubusercontent.com/54186610/225756448-7a67c9ec-c49b-4ac5-80a3-40e410a1e04f.png)
![srsUE](https://user-images.githubusercontent.com/54186610/225756476-c5c06dee-fd2f-49ee-bb47-d15ffbb055be.png)

**Comment by romilbalar** [comment]
@jqhu27 I can definitely confirm that those messages do seem to be part of even successful builds. Unless it is a blocking error, I would suggest you try to go ahead with the installation procedure. I do not believe I have come across this issue due to hardware limitations.
