### ISSUE TITLE
Hardware requirments

### ISSUE THREAD

**Issue by jqhu27** [openaicellular/oaic#81]
Is a 10 Gbps NIC necessary to run the project?

**Comment by jgaeddert** [comment]
Ah, I see this is covered in #80

**Comment by jqhu27** [comment]
Thanks for your reply. I am using two x310s. Do you have any idea about the https://github.com/openaicellular/oaic/issues/80?

**Comment by romilbalar** [comment]
Refer to #80, thanks!
