### ISSUE TITLE
Failed to establish socket connection to NodePort service-ricplt-e2term-sctp-alpha

### ISSUE THREAD

**Issue by jqhu27** [openaicellular/oaic#83]
When I run srsENB with x310, it keeps showing "[COMN  ] [I] [0] Failed to establish socket connection to 10.109.190.8". I use `kubectl get svc -n ricplt` and it shows that the cluster IP, 10.109.190.8, is a NodePort corresponding _service-ricplt-e2term-sctp-alpha_. 

When I installed the kubernetes, I used the shared WiFi from TP-Link in order to fix the IP address. Could it be the reason why the connection failed? 

Any information or help would be arrpeciated.

![Screenshot from 2023-03-22 11-14-40 copy](https://user-images.githubusercontent.com/54186610/226954872-ae82ffbc-278c-401e-a4b3-98ef4ab7ef8a.png)
![Screenshot from 2023-03-22 11-29-30](https://user-images.githubusercontent.com/54186610/226955346-3e5061e9-b54a-4737-bdad-8327e6fbc52d.png)

**Comment by joshuamoorexyz** [comment]
If you have not moved past this issue could you please check to make sure all the pods have started with "kubectl get pods -A". The e2term pod should be in the running state

**Comment by jqhu27** [comment]
Hi, thanks for your information. I have solved this problem by fixing the kubernetes IP address when install it.

**Comment by aksyristos** [comment]
> I have solved this problem by fixing the kubernetes IP address when install it.

Can you explain more in depth what it was that you did? Because I ran into the same error.

**Comment by casperfox** [comment]
> Hi, thanks for your information. I have solved this problem by fixing the kubernetes IP address when install it.

I am having the same issue, and would like to know more on how exactly you fixed this.
