### ISSUE TITLE
Automating OAIC installation Procedures

### ISSUE THREAD

**Issue by connor01M** [openaicellular/oaic#96]
I've attempted to automate the deployment and installation of the RIC, srsRan, and the kpi xapp but I am continually running into errors. Could someone else attempt to run these python scripts and give me some feedback? The first script automates everything up to sudo srsepc but seems to repeatedly fail during the "sudo make -j`nproc`" command (I've only ever gotten it to work with make -j8 so the script now uses that command instead). You will need to manually run the en-gNB and UE in ZeroMQ Mode but everything else should be automated. The second script should ideally deploy the kpi xapp but it also has not been working.
![image](https://github.com/openaicellular/oaic/assets/77762053/9bee22dc-f169-4dc0-902a-ac95f6d1b812)

[DeployRICGNB.txt](https://github.com/openaicellular/oaic/files/11760234/DeployRICGNB.txt)
[HostDeployKPIXapp.txt](https://github.com/openaicellular/oaic/files/11760235/HostDeployKPIXapp.txt)

**Comment by CommoDor64** [comment]
This proper won't solve your issues, but you might refer here.
I wanted to push an initiative to have a proper automated deployment using known tools.
As an example I also present an example, maybe the reference there can actually help you.

#73

**Comment by connor01M** [comment]
@CommoDor64 could you test this out

**Comment by connor01M** [comment]
[DeployRICGNBFinal.txt](https://github.com/openaicellular/oaic/files/11860522/DeployRICGNBFinal.txt)
[HostDeployKPIXappFinal.txt](https://github.com/openaicellular/oaic/files/11860523/HostDeployKPIXappFinal.txt)
[GNBsetupFinal.txt](https://github.com/openaicellular/oaic/files/11860524/GNBsetupFinal.txt)
[UEsetupFinal.txt](https://github.com/openaicellular/oaic/files/11860525/UEsetupFinal.txt)
