### ISSUE TITLE
Deploying nexran & kpimon on the same machine

### ISSUE THREAD

**Issue by aksyristos** [openaicellular/oaic#99]
More of a question than an issue.
KPIMON is deployed while using the srsRAN suite, while Nexran uses srslte.

Will there be compatibility issues if I try to deploy both xApps on the same machine (since they use the same executables)? 
And if not which SRS should I use to deploy both?

**Comment by nathanstep55** [comment]
NexRAN and KPIMON will work if the version of srsRAN used implements the NexRAN and KPM service models. You should be able to deploy both on the same machine if you use the srsRAN-e2 which is included in the oaic repository. srslte is the older name for srsRAN.

**Comment by aksyristos** [comment]
I tried deploying them both using srsRAN-e2 and NexRAN and I don't get the right bandwidth metrics on the iperf test.
Specifically I get ~55 Mbits/sec Bandwidth and it stays there even after running zmqoneue.sh and the slice swap commands.

On srslte the test and the deployment work fine though.

**Comment by joshuamoorexyz** [comment]
Nexran does not work with the srsran provided that is why it uses a different srslte as you said previously. If you wanted this capability you would find more luck with this by trying kpimon on the version of srslte that nexran currently works with, but i have not tested. The KPM service model is the same version, but nexran uses a modified kpm service model. Let me know if it works!
